package Server;

import Util.Network.Packet;

// wraps a packet together with the client who sent it.
// this lets the packetbroker know who sent each packet so it can handle things like login,
// group routing, and sending responses back to the right client.
// sender is null if the packet was generated by the server itself (e.g. a join/leave notification).
public class PacketCarrier
{
	public final Packet packet;
	public final ClientProxy sender; // null = server-generated

	public PacketCarrier(Packet packet, ClientProxy sender)
	{
		this.packet = packet;
		this.sender = sender;
	}
}
